/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebascomponentes;

/**
 *
 * @author Eduardo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        relojBean1 = new Reloj.RelojBean();
        labelHoraAlarma = new javax.swing.JLabel();
        textFieldAlarma = new javax.swing.JTextField();
        botonEstablecer = new javax.swing.JButton();
        labelAlarma = new javax.swing.JLabel();
        labelFormato = new javax.swing.JLabel();
        radioBoton12 = new javax.swing.JRadioButton();
        radioBoton24 = new javax.swing.JRadioButton();
        labelHoraAlarmaEstablecida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RELOJ CON ALARMA");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        relojBean1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relojBean1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        relojBean1.addHoraAlarmaListener(new Reloj.RelojBean.HoraAlarmaListener() {
            public void capturarHoraAlarma(Reloj.RelojBean.HoraAlarmaEvent evt) {
                relojBean1CapturarHoraAlarma(evt);
            }
        });
        relojBean1.addHoraNoAlarmaListener(new Reloj.RelojBean.HoraNoAlarmaListener() {
            public void capturarHoraNoAlarma(Reloj.RelojBean.HoraNoAlarmaEvent evt) {
                relojBean1CapturarHoraNoAlarma(evt);
            }
        });

        labelHoraAlarma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelHoraAlarma.setForeground(new java.awt.Color(102, 102, 153));
        labelHoraAlarma.setText("HORA DE ALARMA");

        textFieldAlarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlarmaActionPerformed(evt);
            }
        });

        botonEstablecer.setText("Establecer");
        botonEstablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstablecerActionPerformed(evt);
            }
        });

        labelAlarma.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelAlarma.setForeground(new java.awt.Color(255, 51, 51));
        labelAlarma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAlarma.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelFormato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelFormato.setForeground(new java.awt.Color(102, 102, 153));
        labelFormato.setText("FORMATO RELOJ");

        buttonGroup1.add(radioBoton12);
        radioBoton12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioBoton12.setText("12 h.");
        radioBoton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioBoton12MouseClicked(evt);
            }
        });
        radioBoton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton12ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioBoton24);
        radioBoton24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        radioBoton24.setSelected(true);
        radioBoton24.setText("24 H.");
        radioBoton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioBoton24MouseClicked(evt);
            }
        });
        radioBoton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBoton24ActionPerformed(evt);
            }
        });

        labelHoraAlarmaEstablecida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelHoraAlarmaEstablecida.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlarma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(relojBean1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFormato)
                                .addGap(30, 30, 30)
                                .addComponent(radioBoton24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBoton12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelHoraAlarma)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonEstablecer))
                            .addComponent(labelHoraAlarmaEstablecida, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(relojBean1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFormato)
                    .addComponent(radioBoton12)
                    .addComponent(radioBoton24))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoraAlarma)
                    .addComponent(textFieldAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEstablecer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(labelHoraAlarmaEstablecida, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelAlarma, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAlarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlarmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlarmaActionPerformed

    private void botonEstablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstablecerActionPerformed
        // TODO add your handling code here:
        String establecerAlarma = textFieldAlarma.getText();
        relojBean1.setAlarma(establecerAlarma);
        textFieldAlarma.setText(null);
        labelHoraAlarmaEstablecida.setText("Alarma establecida a las "+establecerAlarma+" horas");
    }//GEN-LAST:event_botonEstablecerActionPerformed

    private void radioBoton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBoton12ActionPerformed

    private void radioBoton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBoton12MouseClicked
        // TODO add your handling code here:
        relojBean1.setFormato(false);
    }//GEN-LAST:event_radioBoton12MouseClicked

    private void radioBoton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioBoton24MouseClicked
        // TODO add your handling code here:
        relojBean1.setFormato(true);
    }//GEN-LAST:event_radioBoton24MouseClicked

    private void relojBean1CapturarHoraAlarma(Reloj.RelojBean.HoraAlarmaEvent evt) {//GEN-FIRST:event_relojBean1CapturarHoraAlarma
        // TODO add your handling code here:
        labelAlarma.setText("ALARMA SONANDO");
        labelHoraAlarmaEstablecida.setText(null);
    }//GEN-LAST:event_relojBean1CapturarHoraAlarma

    private void relojBean1CapturarHoraNoAlarma(Reloj.RelojBean.HoraNoAlarmaEvent evt) {//GEN-FIRST:event_relojBean1CapturarHoraNoAlarma
        // TODO add your handling code here:
        labelAlarma.setText(null);
    }//GEN-LAST:event_relojBean1CapturarHoraNoAlarma

    private void radioBoton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBoton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBoton24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEstablecer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAlarma;
    private javax.swing.JLabel labelFormato;
    private javax.swing.JLabel labelHoraAlarma;
    private javax.swing.JLabel labelHoraAlarmaEstablecida;
    private javax.swing.JRadioButton radioBoton12;
    private javax.swing.JRadioButton radioBoton24;
    private Reloj.RelojBean relojBean1;
    private javax.swing.JTextField textFieldAlarma;
    // End of variables declaration//GEN-END:variables
}
